["pyproject.toml".tool.black]
line-length = 79
skip-string-normalization = true

[[".pre-commit-config.yaml".repos]]
yaml = """
  -   repo: https://github.com/psf/black
      hooks:
      -   id: black
"""
